### PR TITLE
FIX: clear appCache entries on run/update app requests using Services.evictEntries

### LINKED ISSUE #66: Clearing App Cache
Seems like apps don't have a separated cache (correct me if I am wrong) in B2G, which makes cleaning cache for just one app _hard_.

Some ideas:
- Clearing the cache when the user _updates_ an app. Might have unexpected results, as other apps that weren't updated will also be reset.
- An option to `Clear Cache on Launch`, similar to `JS Console`.
- Alternatives, like changing install flow (to give apps a new ID on install), experimenting.

What are your thoughts on that, @dangoor, @mykmelez ?

### PR DESCRIPTION
**Pull request by rpl**
clear appCache entries on run app requests on run / update user requests (should fix #66)

### CODE REVIEW

File: prosthesis/content/dbg-simulator-actors.js [hunk 1]
```diff
@@ -159,6 +159,8 @@ SimulatorActor.prototype = {
         }
       },
       tryAppReloadByOrigin: function(origin, cb) {
+        debug("RUNAPP: clear all appCache entries");
+        Services.cache.evictEntries(Ci.nsICache.STORE_OFFLINE);
```
Comment (ochameau) [inline prosthesis/content/dbg-simulator-actors.js]: By doing so, you will remove cache for all apps.
You can focus on one particular app by doing something like:

```
var cacheService = Cc["@mozilla.org/network/application-cache-service;1"].
                            getService(Ci.nsIApplicationCacheService);
cacheService.discardByAppId(appId, false);
```

See this IDL for more info:
http://mxr.mozilla.org/mozilla-central/source/netwerk/base/public/nsIApplicationCacheService.idl#72

Comment (rpl) [inline prosthesis/content/dbg-simulator-actors.js]: awesome! it's much much better :-)

in the last change I've updated this pull request to use DOMApplicationRegistry._clearPrivateData (which sends an async request to an application cache service observer)

**Comment by rpl** [comment]
@ochameau awesome! it's much much better :-)

in the last change I've updated this pull request to use DOMApplicationRegistry._clearPrivateData (which sends an async request to an application cache service observer)

**Comment by ochameau** [comment]
You should not call clearPrivateData either ;-)
As it also remove app permission:
http://mxr.mozilla.org/mozilla-central/source/extensions/cookie/nsPermissionManager.cpp#172
`cacheService.discardByAppId` does **exactly** what you want to do, no more, no less.

**Comment by rpl** [comment]
@ochameau I've pushed another change:
now I use cacheService.dicardByAppId directly.

I was a bit confused because it always raises an exception
and I thought I'm not using it correctly (and I've not found any javascript code on mxr which it actually call it directly as we do now),
even if it actually works (which I know because all appCache entries are refreshed on an app window reload)

I put a comment so we can remember why it's surrounded by its own try/catch but we don't print its exception into the debugging logs.

**Comment by mykmelez** [comment]
I don't think we should do this by default, since that would make it impossible to test ordinary reinstallation of an app, which doesn't clear these entries. But I do think we should make it possible to do this. Now that we have a Ctrl/Cmd-R shortcut for refreshing an app, how about we add a Shift-Ctrl/Cmd-R variant that also clears this cache?

**Comment by rpl** [comment]
@mykmelez I like it!
 just pushed: added "Refresh App and Clear AppCache" menu item and "shift
accel R" keyboard shortcut

**Comment by mykmelez** [comment]
Hmm, this feature is hidden in the browser, and I think we should do the same in the Simulator, at least initially. I.e. add the keyboard shortcut but don't add a menu item for it. That makes it less discoverable, which I don't like. But it makes it possible to evolve the feature a bit before we expose it more (f.e. to clear other caches), which I do like. Since it feels like there's more work to do here to figure out exactly what developers want from a "refresh harder" command!

**Comment by rpl** [comment]
@mykmelez sounds good, I've removed menu item and its locale entities.

File: prosthesis/content/shell.js [hunk 2]
```diff
@@ -104,3 +110,25 @@ function simulatorAppUpdate() {
     }
   }, "r2d2b2g:app-update", null);
 }
+
+function simulatorClearAppCache(appId) {
+    let localId = DOMApplicationRegistry.webapps[appId].localId;
```
Comment (mykmelez) [inline prosthesis/content/shell.js]: This function should use two-space indent.

File: prosthesis/content/shell.js [hunk 3]
```diff
@@ -104,3 +110,25 @@ function simulatorAppUpdate() {
...
+
+    if (!localId) {
+        return;
+    }
+
+    try {
+        let cacheService = Cc["@mozilla.org/network/application-cache-service;1"].
+            getService(Ci.nsIApplicationCacheService);
+        cacheService.discardByAppId(localId, false);
```
Comment (mykmelez) [inline prosthesis/content/shell.js]: Nit: in Mozilla code such multi-line statements are conventionally formatted:

```
    let cacheService = Cc["@mozilla.org/network/application-cache-service;1"].
                       getService(Ci.nsIApplicationCacheService);
    cacheService.discardByAppId(localId, false);
```

But in this case it isn't useful to assign the result to a local variable since it's only ever used once, and this can be simply:

```
    Cc["@mozilla.org/network/application-cache-service;1"].
      getService(Ci.nsIApplicationCacheService).discardByAppId(localId, false);
```

File: prosthesis/content/shell.js [hunk 4]
```diff
@@ -104,3 +110,25 @@ function simulatorAppUpdate() {
...
+    } catch(e) {
+        // NOTE: currently cacheService.discardByAppId always raise an expection
+        // even if it's working correctly (and cache entries are refreshed on app
+        // window reload)
+        // EXCEPTION on localId NNNN: [Exception... "Component returned failure code: 0x8000ffff \
+        // (NS_ERROR_UNEXPECTED) [nsIApplicationCacheService.discardByAppId]" \
+        // nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)" ...
+        // debug("EXCEPTION on localId " + localId + ": " + e);
```
Comment (mykmelez) [inline prosthesis/content/shell.js]: The last four lines of this comment look like something left over from an earlier comment. Are they still meant to be here?

File: prosthesis/content/shell.xul [hunk 5]
```diff
@@ -44,12 +44,17 @@
   <commandset id="mainCommandSet">
     <command id="quitSimulatorCmd" oncommand="goQuitApplication()"/>
     <command id="refreshAppCmd" oncommand="simulatorAppUpdate()"/>
+    <command id="refreshAppAndClearAppCacheCmd" oncommand="simulatorAppUpdate(true)"/>
```
Comment (mykmelez) [inline prosthesis/content/shell.xul]: Nit: it'd be nice if _refreshAppAndClearAppCache_ was a bit shorter. The equivalent in Firefox is _ReloadSkipCache_, so perhaps this could be _refreshClearCacheCmd_?

File: prosthesis/content/shell.js (hunk 4 above)
Comment (rpl) [inline prosthesis/content/shell.js]: @mykmelez here I'm not sure how we can handle this "issue" (which apparently didn't present any side-effects):
- just leave this comment (to remember why we catch an exception without report any error)
- print an error linked to an open issue number on github to track this problem (and to remember that we're aware of the issue)

**Comment by mykmelez** [comment]
> @mykmelez here I'm not sure how we can handle this "issue" (which apparently didn't present any side-effects):
> - just leave this comment (to remember why we catch an exception without report any error)
> - print an error linked to an open issue number on github to track this problem (and to remember that we're aware of the issue)

I think a comment is fine! I just thought perhaps the first three lines of the comment where what you intended to include, while the last four lines were for your help while debugging the problem. But I understand now that you want to include all that information in the comment, which is not a problem!

In that case, the only line I might remove is the last one, since it is just a commented-out _debug_ call rather than actual information about the problem.
